/**:
  autocube_client_node:
    ros__parameters:
      address: "autocube.local:5050"
      # address: "127.0.0.1:5050"
      user_cmd_topic: "command/user_command"
      battery_type: 0 # 0:use average; 1: use battery1; 2: use battery2;
      battery1_topic: "system_status_broadcaster/battery1"
      battery2_topic: "system_status_broadcaster/battery2"
      twist_topic: "twist"
      twist_type: "Twist" # Twist, TwistStamped, TwistWithCovariance, TwistWithCovarianceStamped, Odom
      json_topic: "autocube/client_json"
      autocube_json_topic: "autocube/cmd_json"